### ISSUE TITLE
undefined: lockImpl

### ISSUE THREAD

**Issue by ppbrown** [danjacques/gofslock#1]
Hello,

I'm using go 1.10.1 on solaris.

$ go build
# _/tmp/gofslock/fslock
./lock.go:87:20: undefined: lockImpl

**Comment by ppbrown** [comment]
Update:
I added "solaris" to the build line in lock_posix.

Then I get the following errors:
# _/tmp/gofslock/fslock
./lock_posix.go:101:11: undefined: syscall.LOCK_NB
./lock_posix.go:103:12: undefined: syscall.LOCK_SH
./lock_posix.go:105:12: undefined: syscall.LOCK_EX
./lock_posix.go:108:12: undefined: syscall.Flock


This is presumably because Solaris is SYSV based instead of BSD, so it wants to use lockf, instead of flock?

Its rather ironic that you call the file "lock_posix", becasue the POSIX STANDARD, specifies use of lockf, NOT flock (which is BSD only), I believe.

**Comment by danjacques** [comment]
Heh yeah, that's fair. I named it "posix" more b/c it works on Mac, Linux, and FreeBSD, and I don't know a better single word that covers those platforms. I hadn't considered Solaris.

You are correct - your build is failing because those system calls don't exist on Solaris, so the constants aren't defined. The build doesn't *want to use* `lockf` - there is no code to call `lockf`. Adding "solaris" to that file attempts to build for Solaris using `flock` semantics which, as you note, can not work.

I built this library to support the Chromium project which, unfortunately, does not target Solaris, so Solaris support was not something on my mind.  If you'd like to offer a pull request, I'd be happy to incorporate it!

**Comment by ppbrown** [comment]
If im understanding the Go documentation, the ACTUAL POSIX complient call, is
syscall.FcntlFlock()

documented here:

https://golang.org/src/syscall/flock.go

This should work on all the current systems you run on, plus solaris.

**Comment by ppbrown** [comment]
For your convenience, someone's contributed code to this other project, seems to be a good demonstration of usage.

https://github.com/coreos/etcd/issues/2742

**Comment by ppbrown** [comment]
I have version of the code that "compiles" now.
however, there doesnt seem to be any simple test case, so I have no idea if it works, or stays true to the original intent of the code.

**Comment by danjacques** [comment]
Good to hear! I developed against [lock_test.go](https://github.com/danjacques/gofslock/blob/master/fslock/lock_test.go) suite. Granted aren't simple, but they are pretty thorough and comprehensive assertions of proper locking behavior. If your code passes that suite, I'd consider it conforming.

**Comment by ppbrown** [comment]
Hm.
I dont see comments in that test, for how to invoke the tests?

**Comment by danjacques** [comment]
Invocation is a standard "go test", so:

```sh
go test github.com/danjacques/gofslock/fslock
```

You can isolate a specific test case using `-run <REGEX>`, for example, to run the simplest test, you can add: `-run '^TestConcurrent$`

You'll want to run against different CPU counts to test various concurrency models, so I'd recommend also adding the `cpu=1,2,4,8` flag to run the suite w/ that many logical CPUs.

**Comment by ppbrown** [comment]
A heads up for you... I'm now trying to get a clean, portable implementation of Fcntl() into the Go code.
Which would then, among other things, implement Fcntl(fd, F_SETLK, ), and so on :)

**Comment by danjacques** [comment]
ppbrown@ submitted a fix for Solaris that has been merged, so I'm going to go ahead and close this issue.
